# SPDX-FileCopyrightText: 2023 C. J. Howard
# SPDX-License-Identifier: GPL-3.0-or-later

name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            preset: win64-release
          # - os: ubuntu-latest
            # preset: linux64-release
    
    steps:
    - uses: actions/checkout@v3
      
    - name: CMake configure
      run: cmake --preset ${{matrix.preset}}
      
    - name: CMake build
      run: cmake --build --preset ${{matrix.preset}}
