# SPDX-FileCopyrightText: 2023 C. J. Howard
# SPDX-License-Identifier: GPL-3.0-or-later

name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            preset: win64
          # - os: ubuntu-latest
            # preset: linux64
    
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    
    - name: CMake configure
      run: cmake --preset ${{matrix.preset}}-release
    
    - name: Install glad requirements
      run: pip install -r build/${{matrix.preset}}/_deps/glad-src/requirements.txt
    
    - name: CMake build
      run: cmake --build --preset ${{matrix.preset}}-release
